config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'payment_requests#index'

  resources :payment_requests do
    post 'accept_payment_request'
    post 'reject_payment_request'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor/payment_request.rb
# frozen_string_literal: true

module Contractor
  class PaymentRequest < ApplicationRecord
    self.table_name = 'contractor_payment_requests'

    enum status: %i[pending accepted rejected]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/payment_requests_controller.rb
# frozen_string_literal: true

class PaymentRequestsController < ApplicationController
  before_action :set_payment_request, only: %i[accept_payment_request reject_payment_request]

  def index
    @payment_requests = Contractor::PaymentRequest.all
  end

  def accept_payment_request
    if @payment_request.update(status: :accepted)
      Publisher.publish('payment_requests', @payment_request.attributes)
      redirect_to root_path, notice: 'Payment request was successfully accepted.'
    end
  end

  def reject_payment_request
    if @payment_request.update(status: :rejected)
      Publisher.publish('payment_requests', @payment_request.attributes)
      redirect_to root_path, notice: 'Payment request was successfully rejected.'
    end
  end

  private

  def set_payment_request
    @payment_request = Contractor::PaymentRequest.find(params[:payment_request_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_requests/index.html.erb
<h2>Submitted payment requests</h2>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Currency</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_requests.each do |payment_request| %>
    <tr>
      <td><%= payment_request.amount %></td>
      <td><%= payment_request.currency %></td>
      <td><%= payment_request.description %></td>
      <td><%= payment_request.status %></td>
      <td>
        <% if payment_request.pending? %>
          <%= link_to 'Accept', payment_request_accept_payment_request_path(payment_request), method: :post, data: { confirm: 'Are you sure to accept that payment request?' } %>
          <%= link_to 'Reject', payment_request_reject_payment_request_path(payment_request), method: :post, data: { confirm: 'Are you sure to reject that payment request?' } %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>